variable "region" {}
variable "vcn_compartment_id" {}
variable "vcn_display_name" {}
variable "vcn_cidr_block" {}
variable "vcn_dns_label" {}
variable "subnet_compartment_id" {}
variable "subnet_display_name" {}
variable "subnet_cidr_block" {}
variable "subnet_dns_label" {}
variable "vcn_compartment_id" {}
variable "vm_shape_name" {}
variable "vm_image_id" {}
variable "availability_domain" {}
